#!/usr/bin/env bash
# Idempotent data-directory tree creator.
# Usage: setup_data_dir.sh --slot <dev|uat|prod> [--data-root <path>]
#
# Creates the per-slot, per-scope data directory layout and writes
# a LAYOUT.md document describing the tree.

set -euo pipefail

# ── helpers ──────────────────────────────────────────────────────────────
die() { echo "fatal: $*" >&2; exit 1; }

# ── parse args ───────────────────────────────────────────────────────────
slot=""
data_root="${ARTEMIS_DATA_ROOT:-/opt/artemis}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slot) slot="$2"; shift 2 ;;
    --data-root) data_root="$2"; shift 2 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ -z "$slot" ]] && die "--slot is required (dev|uat|prod)"
[[ "$slot" =~ ^(dev|uat|prod)$ ]] || die "slot must be dev, uat, or prod, got: $slot"

# ── directory tree ───────────────────────────────────────────────────────
root="$data_root/$slot"

mkdir -p "$root"
chmod 700 "$root"

for scope in owner-private general; do
  sd="$root/$scope"
  mkdir -p "$sd"/{memory,relational,keys}
  chmod 700 "$sd" "$sd"/memory "$sd"/relational "$sd"/keys
  echo "$scope" > "$sd/.artemis-scope"
  chmod 600 "$sd/.artemis-scope"

  # Encrypted-volume mount point (LanceDB)
  mkdir -p "$sd"/vault
  chmod 700 "$sd"/vault
done

mkdir -p "$root"/{backups,logs}
chmod 700 "$root"/backups "$root"/logs

# ── LAYOUT.md ────────────────────────────────────────────────────────────
cat > "$root/LAYOUT.md" <<LAYOUTEOF
# Data Directory — slot: ${slot}
*Generated by setup_data_dir.sh — do not edit manually*

\`\`\`
<root>/
  <slot>/
    owner-private/      # Owner-personal data (SQLCipher encrypted)
      memory/           #   bitemporal memory DB (M4)
      relational/       #   operational DBs (future)
      keys/             #   key-reference metadata (never the key itself)
      vault/            #   LanceDB on encrypted volume (M2 mount point)
    general/            # Non-personal, shared data
      memory/
      relational/
      keys/
      vault/
    backups/
    logs/
\`\`\`

### Scope visibility
- \`owner-private\`: only the owner runtime process can read/write.
- \`general\`: non-personal system data.
- Guest scopes (\`guest-<id>\`) are provisioned at runtime.
LAYOUTEOF

chmod 600 "$root/LAYOUT.md"

# ── summary ──────────────────────────────────────────────────────────────
echo "Created data directory tree at: $root"
find "$root" -type d | sort | head -c -1
echo
